name: bigdata19.case01
dependencies:
  - python=3.7
  - aiofiles
  - aiohttp
  - fabric
  - lxml
  - pip
  - pyarrow
  - pyspark
  - pyyaml
  - tqdm
  - pip:
      - fabricutils
      - google-cloud-bigquery
